apiVersion: v1
kind: Service
metadata:
  name: frontend-xmart-shopping-app-svc
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 9008
      nodePort: 30000
  type: LoadBalancer
  selector:
    app: frontend-xmart-shopping-app-app
 