apiVersion: v1
kind: Service
metadata:
  name: deliveryapp-service
spec:
  selector:
    app: deliveryapp
  type: loadBalancer
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 4000
    nodePort: 31110